### ISSUE TITLE
[Question] How to stop after succesful run with custom settings?

### ISSUE THREAD

**Issue by 0xphk** [jina-ai/discoart#107]
I've created a init.py with custom settings due to 8G VRAM restrictions. 

The images creates (batch_size=1, n_batches=1) but after it's done, 
it instantly starts doing a second run with default options, which always fails due to VRAM.

I've tested adding exit() and quit() to the python file but no luck.
How to render just that one image with specific settings and exit afterwards?

**Comment by hanxiao** [comment]
cant reproduce.

**Comment by 0xphk** [comment]
Do I have any mistakes in the .py file? When I run the saved .yml file it stops after creating the image, 
running ```python init.py``` starts over with default settings.

```python
#!/usr/bin/env python
from discoart import create, save_config
da = create(
    text_prompts='some prompt',
    width_height=[512,384],
    cut_overview="[7]*400+[4]*600",
    cut_innercut="[4]*400+[7]*600",
    steps=150,
    n_batches=1,
    use_secondary_model=False,
)
save_config(da, 'prompt.yml')
create()
```
