### ISSUE TITLE
Render progress is printed to STDERR

### ISSUE THREAD

**Issue by zhl146** [jina-ai/discoart#118]
I am trying to parse the render progress that looks like this:
` 8%|▊         | 19/250 [01:16<15:30,  4.03s/it]`
but it looks like it's output to stderr instead of stdout.

I can't find the code that prints this, would it be possible to change it so that it prints to stdout?

Thanks!

**Comment by hanxiao** [comment]
hmm, could you help me understand your env? are you using discoart as a python library, in notebook, in docker, or in serving?

**Comment by hanxiao** [comment]
close as #137
