### ISSUE TITLE
Option to change progress refresh for jupyter 

### ISSUE THREAD

**Issue by zhl146** [jina-ai/discoart#131]
The instant previews for jupyter are awesome, but take a lot of of bandwidth. Is it currently possible to tone it down a bit? I don't think it currently respects save_rate. Thanks!

**Comment by hanxiao** [comment]
`0.10.13`, check docstring for `display_rate`, default 1, use larger number

**Comment by zhl146** [comment]
Got it, I hadn't checked the latest doc. Sorry!
