### ISSUE TITLE
Any thoughts on go-big? Stitching?

### ISSUE THREAD

**Issue by zhl146** [jina-ai/discoart#148]
I've had quite a few people ask about go-big mode, which is the stitching implemented by jax-diffusion (huemin). Have you heard about this? Apparently the results are quite good.

**Comment by hanxiao** [comment]
could you send me an example pictures of before/after of Go Big. i'd like to use it as a regression test
this would help me to understand what I should expect after implementing such algorithm
thanks a lot

**Comment by zhl146** [comment]
Images too large to upload to GH lol, will DM them to you over discord :)
Here's an article that Huemin wrote that kind of describes the process and gives a few examples:
https://dreamingcomputers.com/ai-articles/huemin-jax-diffusion-2-7-stitching/

**Comment by entmike** [comment]
These are from LowFuel#6148 on Discord:

https://github.com/lowfuel/progrockdiffusion
https://github.com/lowfuel/DiscoDiffusion-Warp-gobig

I've also been interested in the "gobig" approach with stitching etc.  Would be a great addition to consider either in discoart, or wrapping some logic around it to do in a Python wrapping way.
