### ISSUE TITLE
error in connecting

### ISSUE THREAD

**Issue by SearchingForSea** [jina-ai/discoart#155]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/104902367/183607116-3419ed59-8bdb-4fe4-ab85-8e64548ea143.png">

**Comment by hanxiao** [comment]
plz provide client and server code, what did you send

**Comment by SearchingForSea** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/104902367/183632322-854abdee-fd0a-456a-862b-f2c99a1e06db.png">
I got this step in order.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/104902367/183632444-2694b94b-fb42-4bee-bd27-dad7e0ddf4a8.png">
But got this error when running like this locally.

**Comment by SearchingForSea** [comment]
I want to use it as a serve so the above situation appears in the colab after entering this interface.
<img width="922" alt="image" src="https://user-images.githubusercontent.com/104902367/183634556-f7504c15-2c37-4bdb-8bfe-22604e239990.png">
