### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by KirbyDaMaster** [jina-ai/discoart#16]
Maybe I missed something, im fairly new to running github projects. But this issue is stumping me after a few hours of trying to fight the thing. 

When i run just the default demo
`from discoart import create

da = create()`

i get this error

`D:\Downloads D\discoart-0.2.1\discoart\__init__.py:32: UserWarning: 
        !!!!CUDA is not available. DiscoArt is running on CPU. `create()` will be unbearably slow on CPU!!!!
        Please switch to a GPU device. If you are using Google Colab, then free tier would just work.
        
  warnings.warn(
Traceback (most recent call last):

  File D:\Downloads D\discoart-0.2.1\asdsd.py:3 in <module>
    da = create()

  File D:\Downloads D\discoart-0.2.1\discoart\__init__.py:221 in create
    model, diffusion = load_diffusion_model(

  File D:\Downloads D\discoart-0.2.1\discoart\helper.py:433 in load_diffusion_model
    model.load_state_dict(torch.load(_model_path, map_location='cpu'))

  File ~\anaconda3\lib\site-packages\torch\serialization.py:705 in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:

  File ~\anaconda3\lib\site-packages\torch\serialization.py:242 in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

Now I read it has something to do with not having the model but I am unsure where the model is even missing if it is. Any suggestions?

**Comment by Juliaququ** [comment]
> Maybe I missed something, im fairly new to running github projects. But this issue is stumping me after a few hours of trying to fight the thing.
> 
> When i run just the default demo `from discoart import create
> 
> da = create()`
> 
> i get this error
> 
> `D:\Downloads D\discoart-0.2.1\discoart\__init__.py:32: UserWarning: !!!!CUDA is not available. DiscoArt is running on CPU. `create()` will be unbearably slow on CPU!!!! Please switch to a GPU device. If you are using Google Colab, then free tier would just work.
> 
> warnings.warn( Traceback (most recent call last):
> 
> File D:\Downloads D\discoart-0.2.1\asdsd.py:3 in da = create()
> 
> File D:\Downloads D\discoart-0.2.1\discoart__init__.py:221 in create model, diffusion = load_diffusion_model(
> 
> File D:\Downloads D\discoart-0.2.1\discoart\helper.py:433 in load_diffusion_model model.load_state_dict(torch.load(_model_path, map_location='cpu'))
> 
> File ~\anaconda3\lib\site-packages\torch\serialization.py:705 in load with _open_zipfile_reader(opened_file) as opened_zipfile:
> 
> File ~\anaconda3\lib\site-packages\torch\serialization.py:242 in **init** super(_open_zipfile_reader, self).**init**(torch._C.PyTorchFileReader(name_or_buffer))
> 
> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`
> 
> Now I read it has something to do with not having the model but I am unsure where the model is even missing if it is. Any suggestions?

check your machine whether it has gpu or not:
import torch
torch.cuda.is_available()

**Comment by hanxiao** [comment]
1. since > `0.2`, there is support for CPU. (but it is unbearably slow, too slow I can not even describe it, but hey it works). So it shouldn't be CPU/GPU issue
2. I can not reproduce it on Google Colab free tier new notebook, so it seems like your local env/pytorch issue?

**Comment by KirbyDaMaster** [comment]
My system has an Nvidia rtx 2060 super. I installed the dependencies. I managed to get it to start running one time, but it wasnt running with my GPU so i had to wrestle with the setup some more. Still not sure what it is im doing wrong. I do have torch installed.

**Comment by Juliaququ** [comment]
> My system has an Nvidia rtx 2060 super. I installed the dependencies. I managed to get it to start running one time, but it wasnt running with my GPU so i had to wrestle with the setup some more. Still not sure what it is im doing wrong. I do have torch installed.
I successfully generate pictures on 3090. It takes aroud an hour.

**Comment by hanxiao** [comment]
>  I managed to get it to start running one time, but it wasnt running with my GPU
could it be the files are broken then? because you interrupt in the middle of downloading models? that's why pytorch complained about zip thing.

In this case please delete `${HOME}/.cache/discoart` folder and run again

**Comment by KirbyDaMaster** [comment]
So deleting the .cache/discoart got me running somewhat, but hit another odd error. 

`
2022-07-12 01:56:17,390 - discoart - INFO - preparing models...
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
2022-07-12 01:56:19,482 - discoart - ERROR - 'charmap' codec can't decode byte 0x8d in position 4143: character maps to <undefined>
Traceback (most recent call last):
  File "D:\Downloads D\discoart-0.2.1\discoart\__init__.py", line 235, in create
    do_run(_args, (model, diffusion, clip_models, secondary_model), device=device)
  File "D:\Downloads D\discoart-0.2.1\discoart\runner.py", line 56, in do_run
    pmp = PromptParser(on_misspelled_token=args.on_misspelled_token)
  File "D:\Downloads D\discoart-0.2.1\discoart\helper.py", line 451, in __init__
    self.spell.word_frequency.load_words(
  File "C:\Users\camre\anaconda3\lib\site-packages\spellchecker\spellchecker.py", line 492, in load_words
    words = [ensure_unicode(w) for w in words]
  File "C:\Users\camre\anaconda3\lib\site-packages\spellchecker\spellchecker.py", line 492, in <listcomp>
    words = [ensure_unicode(w) for w in words]
  File "D:\Downloads D\discoart-0.2.1\discoart\helper.py", line 451, in <genexpr>
    self.spell.word_frequency.load_words(
  File "C:\Users\camre\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4143: character maps to <undefined>
Loading model from: C:\Users\camre\anaconda3\lib\site-packages\lpips\weights\v0.1\vgg.pth
`

Also i still can't get torch.cuda.is_available() to return true

**Comment by hanxiao** [comment]
at this point, i dont think your question is related to DiscoArt, look like you have a wrongly setup dev env, which you may want to google ` UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4143: character maps ` especially the utf-8 settings part.

Also since you are using Windows, then the easiest way is to use DiscoArt is in Docker not https://github.com/jina-ai/discoart#run-in-docker
