### ISSUE TITLE
How to set up "name-docarray"?

### ISSUE THREAD

**Issue by SearchingForSea** [jina-ai/discoart#164]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/104902367/183902415-e104e361-2b41-4947-a26b-a3b4db9eef0a.png">
How to set up "name-docarray"?

**Comment by OverStruck** [comment]
I take it you're not a developer?
You don't _have to_ set it up. As the image you posted says, `name-docarray` is the name of the run. If you leave it empty a random name will be generated which will work just fine.

If you do want to specify it, you can do so in your `settings.yml` by setting `name_docarray`.

Likewise doing it in code will work:
`da = create(name_docarray='name')`

**Comment by SearchingForSea** [comment]
> 我想你不是开发者？ 您不必_设置_它。正如您发布的图片所说，`name-docarray`是运行的名称。如果您将其留空，则会生成一个随机名称，该名称可以正常工作。
> 
> 如果你确实想指定它，你可以在你`settings.yml`的设置中这样做`name_docarray`。
> 
> 同样在代码中这样做也可以： `da = create(name_docarray='name')`

Thank you very much.
