### ISSUE TITLE
在Docker运行，使用 Jupyter 笔记本中执行da = create()    (Run in Docker with da = create() in Jupyter notebook)

### ISSUE THREAD

**Issue by china0boy** [jina-ai/discoart#188]
![image](https://user-images.githubusercontent.com/88187914/195962029-7156fd4f-e849-4dda-99eb-2fd3caa84869.png)
上面是我截屏的报错信息（Above is my screenshot of the error message）

File /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:925, in Module.to.<locals>.convert(t)
    922 if convert_to_format is not None and t.dim() in (4, 5):
    923     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
    924                 non_blocking, memory_format=convert_to_format)
--> 925 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

我是新手，我应该怎么办，在线等，求求

**Comment by aiyy03** [comment]
请问解决了吗
