### ISSUE TITLE
feat: Can we add a GUI Interface for this project? 

### ISSUE THREAD

**Issue by ai-naymul** [jina-ai/discoart#194]
In this project, I saw that creating the art is only available in the command line. It would better if there is a GUI interface to use the project. I need some help to add that feature. can we work on this feature?

@JoanFM

**Comment by JoanFM** [comment]
We do not have plans to add features to this project now

**Comment by ai-naymul** [comment]
> We do not have plans to add features to this project now

Let me know if you plan that in the future.
