### ISSUE TITLE
How long does it take your GPU to run the demo?

### ISSUE THREAD

**Issue by davidhaley** [jina-ai/discoart#2]
Good evening,

Cool project, thank you!

How long should the demo take to process? It's currently running at ~`2.00/it` for me with a 3080.

```
from discoart import create

da = create()
```

After first running it, I received:

```
RuntimeError: CUDA out of memory. Tried to allocate 960.00 MiB (GPU 0; 9.78 GiB total capacity; 5.08 GiB already allocated; 785.88 MiB free; 6.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
So, I followed the instructions and ran the following (and it worked):

`PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:793MiB python main.py`

NVidia GTX 3080
Driver Version: 515.48.07
CUDA Version: 11.7

**Comment by davidhaley** [comment]
Update: Oops, I thought it was 7 minutes; however, it's still not finished.

![image](https://user-images.githubusercontent.com/11729897/176985988-3e4a5910-c3d2-4663-826e-6f38f014582d.png)

**Comment by hanxiao** [comment]
yep. that's normal. Diffusion is slow. 

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2041322/176988490-957006ef-a9bf-494e-ab67-4ce79501a737.png">

**Comment by hanxiao** [comment]
If you run on Colab free tier, you only get 5~6s/it

**Comment by davidhaley** [comment]
Cool. Thank you!
