### ISSUE TITLE
Configurable models

### ISSUE THREAD

**Issue by ul** [jina-ai/discoart#3]
First of all, thank you so much for creating discoart! I use it now instead of the original Disco Diffusion notebook as I don't need animation, and my notebook looks much tidier now.

IIUC models are hardcoded there https://github.com/jina-ai/discoart/blob/a52082b6bf5e8f375247e09560c82bf4728c06d3/discoart/helper.py#L86 Are there any plans to make them configurable?

**Comment by hanxiao** [comment]
ah i see, good point! will expose them on weekend

**Comment by hanxiao** [comment]
this is fixed and rolled out in `0.0.14` please update via `pip install -U discoart`

**Comment by ul** [comment]
Thank you!
