### ISSUE TITLE
Progress bar isn't working on paperspace.com

### ISSUE THREAD

**Issue by adieyal** [jina-ai/discoart#33]
![Screenshot from 2022-07-15 16-25-09](https://user-images.githubusercontent.com/420786/179243665-5ea089e8-e886-4991-882b-3eaa23ce2fcf.png)

Any idea how I can fix this?

**Comment by hanxiao** [comment]
could be jupyter notebook problem, can i know the jupyter version? something like this in the cell?

```
!jupyter --version
```

**Comment by hanxiao** [comment]
try 

```
!pip install ipywidgets
```

**Comment by adieyal** [comment]
> !jupyter --version

Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.15.0
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.10.0
jupyter_server   : 1.18.0
jupyterlab       : 3.4.3
nbclient         : 0.6.4
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.3.0

**Comment by adieyal** [comment]
> try
> 
> ```
> !pip install ipywidgets
> ```

No dice - I found this in the javascript console, do you think it might be related?

Error displaying widget vendors-d18a9567.ee921a909c5c6e2baccc.js:2:73079
Error: Host is not attached.
    attach https://console.paperspace.com/ide/vendors-445441d3.ee921a909c5c6e2baccc.js:2
    renderModel https://console.paperspace.com/ide/vendors-f64a56cf.ee921a909c5c6e2baccc.js:2
vendors-d18a9567.ee921a909c5c6e2baccc.js:2:73079
Error displaying widget vendors-d18a9567.ee921a909c5c6e2baccc.js:2:73079
Error: Host is not attached.
    attach https://console.paperspace.com/ide/vendors-445441d3.ee921a909c5c6e2baccc.js:2
    renderModel https://console.paperspace.com/ide/vendors-f64a56cf.ee921a909c5c6e2baccc.js:2
vendors-d18a9567.ee921a909c5c6e2baccc.js:2:73079

**Comment by adieyal** [comment]
> hmm, looks like tqdm compatible problem with whatever customized notebook in Paperspace.
> 
> Can try to figure it out but seems out of scope of DiscoArt

Thanks - agreed that it is out of scope, I was just wondering whether you had an idea. Re tqdm, I do see a progress bar when models are being downloaded. It only happens during image generation.

Happy to close this issue if needed.

**Comment by keyboardsamurai** [comment]
Possibly same problem here with using it on genesiscloud. Jupyter shows no progress bar on chrome and throws this error when starting to render
```
Exception opening new comm
_handleCommOpen @ jlab_core.fc632a0f38747f007842.js?v=fc632a0f38747f007842:2
await in _handleCommOpen (async)
_handleMessage @ jlab_core.fc632a0f38747f007842.js?v=fc632a0f38747f007842:2
await in _handleMessage (async)
(anonymous) @ jlab_core.fc632a0f38747f007842.js?v=fc632a0f38747f007842:2
Promise.then (async)
_onWSMessage @ jlab_core.fc632a0f38747f007842.js?v=fc632a0f38747f007842:2
```

**Comment by hanxiao** [comment]
i see, fixing now

**Comment by hanxiao** [comment]
no clue, i can't reproduce it on Google colab or self-hosted jupyter notebook and jupyter lab.

Do you guys know what is so special about genesiscloud or paperspace? I have no idea what their env is

**Comment by keyboardsamurai** [comment]
As far as I know, genesiscloud uses stock jupyter. But If you want, we can schedule a time via email where I can give you access to a working sheet.

**Comment by keyboardsamurai** [comment]
One thing I noticed (and what the two providers might have in common) is that they make use of a proxy to connect to the instance that runs the sheet. So maybe some kind of security related issue? (CSRF headers, networking etc)? It used to work with previous versions of discoart though.

**Comment by hanxiao** [comment]
can you do `!node -v` in jupyter?

**Comment by hanxiao** [comment]
@adieyal im going to login to paperspace and debug this.

in the worst case, if i can not make tqdm work, do you guys accept if i implement a poorman solution of progress bar without tqdm? As if it is really about tqdm/notebook i'm afraid i won't be able to solve it inside DiscoArt

**Comment by hanxiao** [comment]
confirmed on paperspace
<img width="609" alt="image" src="https://user-images.githubusercontent.com/2041322/179366718-f296f035-4123-4fd4-95eb-1cb428235e00.png">

**Comment by adieyal** [comment]
> @adieyal im going to login to paperspace and debug this.
> 
> in the worst case, if i can not make tqdm work, do you guys accept if i implement a poorman solution of progress bar without tqdm? As if it is really about tqdm/notebook i'm afraid i won't be able to solve it inside DiscoArt

I'd be happy with any solution. It's not super-critical, but it would nice to get some indication of progress of the image generation.

**Comment by hanxiao** [comment]
i will put this issue on hold, I do have a solution but not a quick solution, it involves refactoring the progress display completely to HTML, will need some time

**Comment by hanxiao** [comment]
manage to reproduce with minimum example on Paperspace, without even installing DiscoArt

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/2041322/179370417-28002a88-4e6a-4fb2-8e26-7b4c8120bbc0.png">

@keyboardsamurai i believe genesiscloud behaves the same?

**Comment by hanxiao** [comment]
i believe i fixed it!

<img width="862" alt="image" src="https://user-images.githubusercontent.com/2041322/179373550-b42930f5-145b-41d7-8185-7640598d858d.png">

**Comment by adieyal** [comment]
amazing! that's awesome, thank you

**Comment by keyboardsamurai** [comment]
@hanxiao NodeJS is not installed on the Jupyter instances at genesiscloud. Executing ``Output()`` works fine. 
Seems to be a slightly different issue after all. Will try the new version once it's out and report back if there are still problems. Thanks you for looking into fixing this.

**Comment by adieyal** [comment]
> amazing! that's awesome, thank you

very helpful for benchmarking Paperspace with Colab instances.
