### ISSUE TITLE
Configurable model cache directory

### ISSUE THREAD

**Issue by nerdyrodent** [jina-ai/discoart#35]
Hi,

At the moment, it looks like the model cache directory is hard coded:

```
cache_dir = f'{expanduser("~")}/.cache/{__package__}'
```

As I already have various model files downloaded to a central, shared directory, I was wondering if it would be possible to make this configurable also?

Thanks!

**Comment by hanxiao** [comment]
make sense, will do in next release

**Comment by hanxiao** [comment]
rolled out in 0.6.5 https://github.com/jina-ai/discoart#environment-variables
