### ISSUE TITLE
create is broken in 0.6.9

### ISSUE THREAD

**Issue by adieyal** [jina-ai/discoart#41]
NameError                                 Traceback (most recent call last)
Input In [6], in <cell line: 3>()
      1 from discoart import create
----> 3 create()

File /usr/local/lib/python3.9/dist-packages/discoart/create.py:164, in create(**kwargs)
    153 from .helper import (
    154     load_diffusion_model,
    155     load_clip_models,
   (...)
    160     logger,
    161 )
    163 device = get_device()
--> 164 model, diffusion = load_diffusion_model(_args, device=device)
    166 clip_models = load_clip_models(
    167     device, enabled=_args.clip_models, clip_models=_clip_models_cache
    168 )
    169 secondary_model = load_secondary_model(_args, device=device)

File /usr/local/lib/python3.9/dist-packages/discoart/helper.py:353, in load_diffusion_model(user_args, device)
    350 def load_diffusion_model(user_args, device):
    351     diffusion_model = user_args.diffusion_model
--> 353     _diff_model_name = _get_model_name(diffusion_model)
    354     if _diff_model_name:
    355         rec_size = models_list[_diff_model_name].get('recommended_size', None)

File /usr/local/lib/python3.9/dist-packages/discoart/helper.py:245, in _get_model_name(name)
    244 def _get_model_name(name: str) -> str:
--> 245     for k in models_list.keys():
    246         if k.startswith(name):
    247             return k

NameError: name 'models_list' is not defined

**Comment by hanxiao** [comment]
you are right, fixed in 0.6.11
