### ISSUE TITLE
Docs are unclear about using a custom diffusion model

### ISSUE THREAD

**Issue by tildebyte** [jina-ai/discoart#47]
I had a great deal of difficulty getting discoart to accept a custom diffusion model, and I feel like the documentation around same could be better.

Relevant info:
- Cheatsheet says "diffusion_model: Diffusion_model of choice."
- README says "DISCOART_MODELS_YAML='path/to/your-models.yml' # use a custom list of models file"
- While poking around in the source I somehow stumbled across "DISCOART_DISABLE_REMOTE_MODELS" (apparently it was added to the README recently)

Searching my way through the source, based on the above, I *eventually* realized that the following would work

```python
    diffusion_model='/full/path/to/CUSTOM_MODEL.pt',
    diffusion_model_config = {
        'attention_resolutions': '32, 16, 8',
        'class_cond': False,
        'image_size': 256,
        'learn_sigma': True,
        'rescale_timesteps': True,
        'noise_schedule': 'linear',
        'num_channels': 128,
        'num_heads': 4,
        'num_res_blocks': 2,
        'resblock_updown': True,
        'use_checkpoint': True,
        'use_fp16': True,
        'use_scale_shift_norm': True,
    }
```

e.g. apparently I *didn't* need either DISCOART_MODELS_YAML or DISCOART_DISABLE_REMOTE_MODELS; I simply had to make certain that the "model name" was, in fact, NOT a "model name" in the strictest sense, but actually a fully-qualified file path (and also provide "diffusion_model_config").

**Comment by hanxiao** [comment]
will update the docs
