### ISSUE TITLE
Cuda memory error with P100 and default settings

### ISSUE THREAD

**Issue by adieyal** [jina-ai/discoart#51]
Sometimes I'm not able to run the default settings on a P100 without out of memory errors? I seem to recalled that this wasn't an issue in earlier versions.

![Screenshot from 2022-07-19 20-43-23](https://user-images.githubusercontent.com/420786/179825615-66d2f62b-e2ec-4e6a-847f-668a250f0a05.png)
![Screenshot from 2022-07-19 20-43-40](https://user-images.githubusercontent.com/420786/179825623-47e98e24-e654-49d7-be4e-9406c95bfde4.png)

**Comment by adieyal** [comment]
I must have misunderstood how batch_size works - I didn't realise that it had an impact on VRAM although in hindsight that makes sense. Pity that it is so demanding because it is a very cool feature.

**Comment by hanxiao** [comment]
It is super cool feature, one may think this is only about sampling more images, but it actually improves the image quality (given the loss function is designed to jointly optimizing over all `batch_size`)
