### ISSUE TITLE
How do I get the current job status?

### ISSUE THREAD

**Issue by Tomorrowxxy** [jina-ai/discoart#52]
hello, I read the documentation, but I couldn't find how to get whether the server is currently painting or not.

**Comment by Tomorrowxxy** [comment]
For example: busy, free, etc...
I am using Serving
Thank you

**Comment by hanxiao** [comment]
Use Grafana to setup monitoring and dashboard

![image](https://user-images.githubusercontent.com/2041322/179917319-e8cedda7-d3d0-4ec8-bfab-deceb9555362.png)


You see those endpoints of Prometheus on start? You can curl it via `curl http://0.0.0.0:51002` (e.g. targeting at Gateway)

```bash
# HELP jina_sending_request_seconds Time spent between sending a request to the Pod and receiving the response
# TYPE jina_sending_request_seconds summary
jina_sending_request_seconds_count 0.0
jina_sending_request_seconds_sum 0.0
# HELP jina_sending_request_seconds_created Time spent between sending a request to the Pod and receiving the response
# TYPE jina_sending_request_seconds_created gauge
jina_sending_request_seconds_created 1.658300236876829e+09
# HELP jina_receiving_request_seconds Time spent processing request
# TYPE jina_receiving_request_seconds summary
jina_receiving_request_seconds_count{runtime_name="gateway/rep-0"} 0.0
jina_receiving_request_seconds_sum{runtime_name="gateway/rep-0"} 0.0
# HELP jina_receiving_request_seconds_created Time spent processing request
# TYPE jina_receiving_request_seconds_created gauge
jina_receiving_request_seconds_created{runtime_name="gateway/rep-0"} 1.658300237179372e+09
# HELP jina_number_of_pending_requests Number of pending requests
# TYPE jina_number_of_pending_requests gauge
jina_number_of_pending_requests{runtime_name="gateway/rep-0"} 0.0
```

Then you see statistics as well as pending queries etc.

Teaching users to understand Prometheus and Grafana is out of the scope of this project.
- [Check out the metrics here](https://docs.jina.ai/fundamentals/flow/monitoring-flow/#available-metrics)
- [Learn Grafana](https://grafana.com/)

We do not any support homebrewed status check, using Prometheus + Grafana is the only correct way.

**Comment by Tomorrowxxy** [comment]
> Use Grafana to setup monitoring and dashboard
> 
> ![image](https://user-images.githubusercontent.com/2041322/179917319-e8cedda7-d3d0-4ec8-bfab-deceb9555362.png)
> 
> You see those endpoints of Prometheus on start? You can curl it via `curl http://0.0.0.0:51002` (e.g. targeting at Gateway)
> 
> ```shell
> # HELP jina_sending_request_seconds Time spent between sending a request to the Pod and receiving the response
> # TYPE jina_sending_request_seconds summary
> jina_sending_request_seconds_count 0.0
> jina_sending_request_seconds_sum 0.0
> # HELP jina_sending_request_seconds_created Time spent between sending a request to the Pod and receiving the response
> # TYPE jina_sending_request_seconds_created gauge
> jina_sending_request_seconds_created 1.658300236876829e+09
> # HELP jina_receiving_request_seconds Time spent processing request
> # TYPE jina_receiving_request_seconds summary
> jina_receiving_request_seconds_count{runtime_name="gateway/rep-0"} 0.0
> jina_receiving_request_seconds_sum{runtime_name="gateway/rep-0"} 0.0
> # HELP jina_receiving_request_seconds_created Time spent processing request
> # TYPE jina_receiving_request_seconds_created gauge
> jina_receiving_request_seconds_created{runtime_name="gateway/rep-0"} 1.658300237179372e+09
> # HELP jina_number_of_pending_requests Number of pending requests
> # TYPE jina_number_of_pending_requests gauge
> jina_number_of_pending_requests{runtime_name="gateway/rep-0"} 0.0
> ```
> 
> Then you see statistics as well as pending queries etc.
> 
> Teaching users to understand Prometheus and Grafana is out of the scope of this project.
> 
> * [Check out the metrics supported by Jina here](https://docs.jina.ai/fundamentals/flow/monitoring-flow/#available-metrics)
> * [Learn Grafana](https://grafana.com/)
> 
> We do not any support homebrewed status check, using Prometheus + Grafana is the only correct way.
After using Unblocking /create request
```
# HELP jina_number_of_pending_requests Number of pending requests
# TYPE jina_number_of_pending_requests gauge
jina_number_of_pending_requests{runtime_name="gateway/rep-0"} 0.0
```
Can't monitor the number of requests being processed anymore

**Comment by Tomorrowxxy** [comment]
> Use Grafana to setup monitoring and dashboard
> 
> ![image](https://user-images.githubusercontent.com/2041322/179917319-e8cedda7-d3d0-4ec8-bfab-deceb9555362.png)
> 
> You see those endpoints of Prometheus on start? You can curl it via `curl http://0.0.0.0:51002` (e.g. targeting at Gateway)
> 
> ```shell
> # HELP jina_sending_request_seconds Time spent between sending a request to the Pod and receiving the response
> # TYPE jina_sending_request_seconds summary
> jina_sending_request_seconds_count 0.0
> jina_sending_request_seconds_sum 0.0
> # HELP jina_sending_request_seconds_created Time spent between sending a request to the Pod and receiving the response
> # TYPE jina_sending_request_seconds_created gauge
> jina_sending_request_seconds_created 1.658300236876829e+09
> # HELP jina_receiving_request_seconds Time spent processing request
> # TYPE jina_receiving_request_seconds summary
> jina_receiving_request_seconds_count{runtime_name="gateway/rep-0"} 0.0
> jina_receiving_request_seconds_sum{runtime_name="gateway/rep-0"} 0.0
> # HELP jina_receiving_request_seconds_created Time spent processing request
> # TYPE jina_receiving_request_seconds_created gauge
> jina_receiving_request_seconds_created{runtime_name="gateway/rep-0"} 1.658300237179372e+09
> # HELP jina_number_of_pending_requests Number of pending requests
> # TYPE jina_number_of_pending_requests gauge
> jina_number_of_pending_requests{runtime_name="gateway/rep-0"} 0.0
> ```
> 
> Then you see statistics as well as pending queries etc.
> 
> Teaching users to understand Prometheus and Grafana is out of the scope of this project.
> 
> * [Check out the metrics supported by Jina here](https://docs.jina.ai/fundamentals/flow/monitoring-flow/#available-metrics)
> * [Learn Grafana](https://grafana.com/)
> 
> We do not any support homebrewed status check, using Prometheus + Grafana is the only correct way.

Hi @hanxiao 
After using Unblocking /create request
```
# HELP jina_number_of_pending_requests Number of pending requests
# TYPE jina_number_of_pending_requests gauge
jina_number_of_pending_requests{runtime_name="gateway/rep-0"} 0.0
```
Can't monitor the number of requests being processed anymore
I want to know the current status of the server drawing (whether it is drawing or not.) in real time through the api. Is there any other way to do this? Thank you

**Comment by hanxiao** [comment]
this is because you enabled "floating" feature, which basically makes `jina_number_of_pending_requests` obsolete, there will be no "pending request" from the gateway's view. Let me give you an example,

imagine you are visiting a restaurant in which only a security guy and a chef. when guests visit the restaurant, the security guy stops people and ask them to wait in line, because the security guy knows there is only one chef inside, and he can not serve too many people. So you have to wait.

But now the chef told the security guy, "let them in, I will handle them" "are you sure you are just one guy?" "I'm sure, bring them in!" The security guy shrugs his shoulder and says "whatever", so he lets everyone in. At this point, there is no queue anymore from the security's perspective.

You must turn off `floating: True` to get the queue back.

So it is pretty normal behavior. [It is also highlighted here](https://github.com/jina-ai/discoart#unblocking-create-request).

<img width="885" alt="image" src="https://user-images.githubusercontent.com/2041322/180623689-92da3920-6d02-46d7-999e-2857e55e92d4.png">

**Comment by hanxiao** [comment]
@jina-ai/team-core
