### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by fallbernana123456** [jina-ai/discoart#53]
from discoart import create
da = create()

RuntimeError: CUDA out of memory. Tried to allocate 960.00 MiB (GPU 0; 7.43 GiB total capacity; 5.67 GiB already allocated; 934.44 MiB free; 5.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

0  Tesla P4            Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   42C    P0    24W /  75W |     10MiB /  7611MiB |      0%      Default

**Comment by hanxiao** [comment]
what discoart version are you using?

**Comment by hanxiao** [comment]
!python -m discoart -v

**Comment by hanxiao** [comment]
Im running a Colab free tier and there is no problem running default `create()` with no args
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/2041322/179927480-63cf763e-2efb-4b9d-919f-818ebe01a16c.png">


I just find out your VRAM is only 7GB, that's not enough to run DiscoArt, consider:
- set `diffusion_model` to smaller one
- use fewer cuts
- use smaller CLIP models

**Comment by fallbernana123456** [comment]
> python -m discoart -v

0.6.11

**Comment by hanxiao** [comment]
version too old
