### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by dblunk88** [jina-ai/discoart#59]
When running on Ubuntu 20.04:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

This happens after the run, assuming it is when it tries to open up the image. Primarily connect to the machine via RDP if it makes a difference.

**Comment by hanxiao** [comment]
um... based on the limited information you provided, i tried to figure out your env. 

my best guess is you are *not* using DiscoArt in notebook *and* you still let it *display/print* the image on the **screen**, which is not possible in general, regardless if it is DiscoArt or other software.

my guess is you are using DiscoArt as a integration library or start it from command line, which has no GUI, in this case please set env var *before* starting DiscoArt: `DISCOART_DISABLE_IPYTHON=1`.

If not sure how to set env var, please google
