### ISSUE TITLE
0.7.3 create bug

### ISSUE THREAD

**Issue by Tomorrowxxy** [jina-ai/discoart#60]
1, 0.7.3 version seems to have errors using serve, the reason should be stop_event and skip_event. Fallback to 0.7.2 version is normal
2,I tried to modify /create api to return state synchronously and execute create asynchronously. Sorry I'm not familiar with Python and jina

**Comment by hanxiao** [comment]
Hi @Tomorrowxxy there is no need to work on 2, as the blocked ticket #28 is already solved in upstream at Jina, we will update discoart accordingly, trust us, our solution is more native.

For 1 i will check

**Comment by hanxiao** [comment]
Could your provide more error traceback/stack for problem 1

**Comment by Tomorrowxxy** [comment]
![image](https://user-images.githubusercontent.com/33508761/180166658-6002f01c-474a-4d9a-9989-4b10a1047fc9.png)
At that time, only this screenshot was kept

**Comment by Tomorrowxxy** [comment]
> 你好@Tomorrowxxy没有必要在 2 上工作，因为阻塞的票#28已经在今天早些时候在 Jina 的上游解决了，我们将相应地更新 discoart，相信我们，我们的解决方案更加原生。
> 
> 对于 1 我会检查

When will it support asynchronous calls to the create api?

**Comment by Tomorrowxxy** [comment]
> Could you provide more error traceback/stack for problem 1

When will it support asynchronous calls to the create api?

**Comment by hanxiao** [comment]
> When will it support asynchronous calls to the create api?

in few hours

**Comment by hanxiao** [comment]
released in 0.7.5

**Comment by hanxiao** [comment]
check here for the usage and consequence https://github.com/jina-ai/discoart#unblocking-create-request
