### ISSUE TITLE
Feature Request: Expose GPU device ID

### ISSUE THREAD

**Issue by zhl146** [jina-ai/discoart#87]
I saw that the code currently does not allow one to select the torch device. Would it be possible to get this as a command line option? I wish to be able to call discoart using python -m discoart --cuda_device=2 or something like that.

Thanks!

**Comment by hanxiao** [comment]
```bash
CUDA_VISIBLE_DEVICES=1 python -m discoart 
```

https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

**Comment by zhl146** [comment]
Mike let me know this was a possibility as well. Thank you!
