### ISSUE TITLE
 RuntimeError: Input a beautiful painting of a singular lighthouse , shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade , trending on artstation . is too long for context length False

### ISSUE THREAD

**Issue by AhmedEwis** [jina-ai/discoart#89]
Hello,

the code was working fine yesterday, today even the default is not working, what is the problem?

**Comment by hanxiao** [comment]
pip install -U discoart

**Comment by BrettWitty** [comment]
I get this same error for version 0.7.19, running through the Docker container. This appears to be the latest and greatest, and no update was made to the discoart package itself when I ran this.

Are we waiting for 0.7.20?

**Comment by hanxiao** [comment]
@BrettWitty nope, you highly likely use the wrong version without `docker pull jinaai/discoart` or to ensure that you use 0.7.19, just `docker run .... jinaai/discoart:0.7.19`, where `...` represents the args I said in the section "Run in Docker" in README

**Comment by BrettWitty** [comment]
Pulling the explicit version in Docker worked. Updating within the `jinaai/discoart` default one claimed to have updated (and `discoart.__version__` confirmed it, but perhaps the Jupyter notebook kernel was a mess).

Thanks!
