### ISSUE TITLE
0.9.0 bug

### ISSUE THREAD

**Issue by Tomorrowxxy** [jina-ai/discoart#98]
![image](https://user-images.githubusercontent.com/33508761/181500568-bc840e55-bdc0-4569-a38c-b9ff5b443d9e.png)
After I upgraded, the service failed to start. Trying to reinstall doesn't work either

**Comment by Tomorrowxxy** [comment]
hello @hanxiao

**Comment by Tomorrowxxy** [comment]
![image](https://user-images.githubusercontent.com/33508761/181500977-b1a9933d-7868-4c89-8a91-c6b4b13c4f6d.png)
hello @hanxiao 
Additional error logs

**Comment by hanxiao** [comment]
update to 0.9.0

**Comment by Tomorrowxxy** [comment]
> update to 0.9.0

Look at the first picture, the current use is 0.9.0

**Comment by hanxiao** [comment]
could you also do pip install -U jina

**Comment by Tomorrowxxy** [comment]
> could you also do pip install -U jina

![image](https://user-images.githubusercontent.com/33508761/181502201-1ca2ea1f-50e8-40b8-b0ff-c1dff5a6abf3.png)
I tried. The problem is still there.

**Comment by Tomorrowxxy** [comment]
I fall back to version 0.7.16 and it works fine

**Comment by hanxiao** [comment]
im confused by this bug, as it shouldn't happen and my fix in #101 should be unnecessary.

nonetheless, i revert the import logic to 0.7.16 and rolled it out to 0.9.1, please try 0.9.1

**Comment by Tomorrowxxy** [comment]
> im confused by this bug, as it shouldn't happen and my fix in #101 should be unnecessary.
> 
> nonetheless, i revert the import logic to 0.7.16 and rolled it out to 0.9.1, please try 0.9.1

![image](https://user-images.githubusercontent.com/33508761/181666625-622b9802-6cb1-4359-bb9c-768309d4f5a9.png)
![image](https://user-images.githubusercontent.com/33508761/181666645-ef6bbc65-3305-442e-af86-39f379e27dc5.png)

hello @hanxiao 
I just updated to 0.9.2 and it looks like there are no more problems 🎉

**Comment by Tomorrowxxy** [comment]
![image](https://user-images.githubusercontent.com/33508761/181673107-9d1b2385-0d98-450e-acf6-0c0d8d5040b7.png)
![image](https://user-images.githubusercontent.com/33508761/181673378-45d84bce-5bf2-47ef-864a-aec59c452c5f.png)

hello @hanxiao 
I have a new problem, but I don't know if it belongs to version 0.9.2. Because in <= 0.7.16 I didn't encounter
1. Unable to use CUDA, see Figure 1 for details
2. Custom flow.yml without env does not work, as in Figure 2
`JINA_MP_START_METHOD='spawn' python -m discoart serve myFlow.yml` This will start and work fine

expect a reply.

**Comment by hanxiao** [comment]
could you try 0.9.3

**Comment by Tomorrowxxy** [comment]
> could you try 0.9.3

I looked at the changes in version 0.9.3 and the main change is to the flow.yml file?
The modified content is the same as in the second image of my last reply. So I feel that there is still a problem

**Comment by hanxiao** [comment]
you can try, it is not as simple as it looks, changing yaml means changing import order, so maybe it solves your problem. i can't try, i can't reproduce your problem

**Comment by Tomorrowxxy** [comment]
> you can try, it is not as simple as it looks, changing yaml means changing import order, so maybe it solves your problem. i can't try, i can't reproduce your problem

After I upgraded to 0.9.3 and deleted the debug log I added, it works fine!
The main performance is: the executors.py file adds the following code
```
from jina import Executor, requests, DocumentArray
**from .helper import logger**
```
After deleting it, it will be fine.
Thank you for your reply.
