### ISSUE TITLE
Option to not not save GIF/Intermediates

### ISSUE THREAD

**Issue by entmike** [jina-ai/discoart#99]
I found the `gif_fps` option which I was hoping if I set to `0`, would not render a GIF, however it just causes a divide by zero error :)

Is there a way we can expose a parameter to not save a GIF or progress PNGs to the filesystem and/or DocumentArray?  They are quite large in size.  If there's already this option, I may have overlooked it.  I can delete the files manually afterwards on my end I suppose, but figured I'd check.

**Comment by hanxiao** [comment]
rolled out in 0.9.1
